# Generated by Django 3.0.5 on 2020-04-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='task',
            new_name='of_task',
        ),
    ]
