# Generated by Django 3.0.5 on 2020-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200420_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='is_accomplished',
            field=models.BooleanField(default=False),
        ),
    ]
