# Generated by Django 3.0.5 on 2020-05-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='img',
            new_name='image',
        ),
    ]
